baseURL = "http://dennoblog.com/"
languageCode = "en-us"
title = "電脳ブログ"
theme = "chunky-poster"

[params]
  homepageImage = "/images/homepage-image.jpg"
  description = "コンピュータシステムからデザインまで"
  images = "pc.png"

[menu]
  [[menu.global]]
    identifier = ""
    name = "Home"
    url = "/"
    weight = 1
  [[menu.global]]
    identifier = ""
    name = "About"
    url = "/about"
    weight = 2

hasCJKLanguage = true
summaryLength = 1
